services:
    zent.sonata.admin.vars:
        class: Zent\VarsBundle\Admin\VarsAdmin
        arguments: [~, Zent\VarsBundle\Entity\Vars, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Vars }
        calls:
            - ["setVarsManager", ["@zent.vars_manager"]]
