services:
    zent_vars.manager:
        class: Zent\VarsBundle\Entity\VarsManager
        arguments:
          - "@doctrine.orm.default_entity_manager"
          - "%zent_vars.class%"
          - "@?zent_vars.cache"

    zent_vars.sonata.admin:
        class: Zent\VarsBundle\Admin\VarsAdmin
        arguments: [~, "%zent_vars.class%", SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: Переменые, label: Список }
        calls:
            - ["setVarsManager", ["@zent_vars.manager"]]

    zent_vars.twig.extension:
        class: Zent\VarsBundle\Twig\Extension\VarsExtension
        properties:
          vars: "@zent_vars.manager"
        tags:
          - { name: twig.extension }
