Zent\VarsBundle\Entity\Vars:
    constraints:
            - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Length:
                min: 3
                max: 30